version: "3.7"

services:
  superset-duckdb:
    build: .
    image: superset-duckdb
    container_name: superset-duckdb
    environment:
      - MOTHERDUCK_TOKEN=${MOTHERDUCK_TOKEN:-}
    ports:
      - "8088:8088"